name: Deploy Infra

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deployInfrastructure:
    runs-on: ubuntu-latest
    environment: Testing
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ '${{ secrets.AWS_ROLE_TO_ASSUME}}' }}
          aws-region: ${{ '${{ secrets.AWS_REGION}}' }}
      - name: Prepare Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.5
      - name: Terraform Init
        working-directory: terraform/
        run: terraform init
      - name: Terraform plan
        working-directory: terraform/
        run: terraform plan
      - name: Terraform apply
        working-directory: terraform/
        run: terraform apply -auto-approve -input=false
